### ISSUE TITLE
DOCSIS som fast internet access teknologi

### ISSUE THREAD

**Issue by gloinul** [tu-stiftelsen/femsmahus2#13]
Skall DOCSIS inkluderas som möjlig teknologi för överläming av Interet access i Lager 1/2 kapitlet?

**Comment by patrikhson** [comment]
Det absolut viktigaste är att detta blir en specifikation av internetaccess.

Hur folk implementerar det som specificeras är ett problem för de som bestämmer sig för att implementera det.

Självklart kan det kanske behövas specifikationer av olika slag som talar om best current practice om hur man gör det, men jag påstår att TU är ganska mycket mindre intresserad av detta än vad man är intresserad av att målbilden, hur internetaccessen är väldefinierad.

Låt marknaden och de som hittar på L2 fortsätta hitta på!

**Comment by gloinul** [comment]
Det här är en reaktion mot att kapitlet idag säger att teknologin skall vara en av dessa som är listad. Håller med om att vi nog inte skall låsa fast vid L1/L2 teknologi. Det som kanske skall klargöras är modellen för Internet Access är att ju att i vissa fall så används en omvandlare som hanterar L1 och L2 omvandling. För att tydliggöra detta så kan man ju jämföra om Internet access överlämningen till en privatkund i en lägenhet är ett 1GB Ethernet interface eller om man får det över en 1 GB ethernet som sitter i ett DOCSIS modem som operatören tillhandahåller. Utrustningen som operatören tillhandahåller för hantera antingen media eller andra tjänster så som IPTV eller telefoni hanteras ju då av operatörens utrustning. Detta gör ju att Internet access specen appliceras på det gränssnitt där Internet Access faktiskt överlämnas. 

Jag noterar att detta dock att problemet med operatörens utrustning och att man som kund inte kan byta ut den då denna t.ex. är den som vet vilken VLAN tag som fiberkonverteringsboxen skall lägga på för att identifiera kunden inte är känd. Men jag ser ingen bra lösning för dessa problem utan att vidare detaljspecificera som verkar svårt att få genomslag hos operatörerna.

**Comment by flindeberg** [comment]
Jag tror att vi har hanterat detta nu. Dvs att L1/L2 lite lämnas därhän och det är krav på L3. 

Håller ni med / inte med?

**Comment by flindeberg** [comment]
Stänger.
