### ISSUE TITLE
Option 18 / 27 för DHCPv6 PD osv #internetaccess

### ISSUE THREAD

**Issue by tobbe-eklov** [tu-stiftelsen/femsmahus2#4]
SOm vi sa på mötet så kanske vi ska kräva persistent lease beroende på lämplig DHCPv6 option.

**Comment by oej** [comment]
Vi behöver kanske fundera på säkerhetsperspektivet som nämndes i mötet.

**Comment by flindeberg** [comment]
Jag uppdaterade dokumentet i samband med mötet, ser det OK ut nu?

**Comment by tobbe-eklov** [comment]
Det är jag som är en klantskalle, det är option 18 och 37 det ska vara....... 27 är fel.

**Comment by flindeberg** [comment]
Uppdaterat!

**Comment by flindeberg** [comment]
Stänger.
