### ISSUE TITLE
Kvar att göra med specifikationen

### ISSUE THREAD

**Issue by flindeberg** [tu-stiftelsen/femsmahus2#7]
Tydliggör i Internetspecifikationen:
- målgrupper, vilka ska tänkas läsa denna spec
- bättre introduktion så att man förstår hur den passar in i helheten
- figurer som introducerar hur saker hänger ihop

**Comment by flindeberg** [comment]
@flindeberg tar fram en figur. Denna borde ligga i inledning / användning / målgrupp så att den kommer in tidigt.

Hur långt "åt höger" går specifikationen egentligen?

**Comment by flindeberg** [comment]
Skilja och trådbundna och icke-trådbundna anslutningar?

**Comment by flindeberg** [comment]
Fixed wireless access?

**Comment by flindeberg** [comment]
Se #14

**Comment by tobbe-eklov** [comment]
Hur går det med beskrivande bilder till specen?

**Comment by flindeberg** [comment]
Ligger på min todo, får inte till så bra bilder med mermaid. Osäker på vägen framåt just nu. @dansarie Har du någon idé?

**Comment by tobbe-eklov** [comment]
Om vi använder .odf-format som grund så kan väl ingen klaga och "alla" kan rita och ändra?

**Comment by flindeberg** [comment]
Finns enklare figur. Vi skapar ny issue om denna inte duger.
