### ISSUE TITLE
RFC för "colors"

### ISSUE THREAD

**Issue by flindeberg** [tu-stiftelsen/femsmahus2#8]
På arbetsmöten har det diskuterats att det finns en RFC för standardiserad VLAN-taggning, s.k. "colors". 

Vilken RFC är detta?

**Comment by dnov-swe** [comment]
Kan det vara 802.1Q? https://en.wikipedia.org/wiki/IEEE_802.1Q

**Comment by flindeberg** [comment]
Kanske?

**Comment by flindeberg** [comment]
Se #14 
Stänger denna.
